//E/E-backend/utils/matchScore.js

const STOPWORDS = new Set([
    'the', 'a', 'an', 'and', 'or', 'but', 'if', 'then', 'else', 'for', 'to', 'of', 'in', 'on',
    'at', 'by', 'with', 'from', 'as', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'this',
    'that', 'these', 'those', 'it', 'its', 'their', 'they', 'he', 'she', 'we', 'you', 'your',
    'our', 'i', 'me', 'my', 'will', 'shall', 'can', 'could', 'should', 'would', 'may', 'might',
    'must', 'not', 'no', 'do', 'does', 'did', 'has', 'have', 'had', 'job', 'role', 'position',
    'company', 'team', 'work', 'experience', 'years', 'year', 'skills', 'required',
    'requirements', 'responsibilities', 'including', 'etc', 'strong', 'ability', 'looking',
    'candidate', 'about', 'with'
]);

function tokenize(text) {
    if (!text) return [];
    return (text.toLowerCase().match(/[a-z0-9+#./]{3,}/g) || [])
        .filter(tok => !STOPWORDS.has(tok));
}

function buildCandidateKeywordSet(user) {
    const parts = [];
    if (user.headline) parts.push(user.headline);
    if (user.about) parts.push(user.about);
    if (user.skills && user.skills.length) parts.push(user.skills.join(' '));
    if (user.experience && user.experience.length) {
        user.experience.forEach(e => {
            if (e.designation) parts.push(e.designation);
            if (e.company_name) parts.push(e.company_name);
        });
    }
    return new Set(tokenize(parts.join(' ')));
}

function buildJobKeywordSet(job) {
    const parts = [job.title, job.description, job.fullDescription].filter(Boolean);
    return new Set(tokenize(parts.join(' ')));
}

/**
 * Builds a keyword set from an actual generated/submitted résumé (CV object shape:
 * fullName, coreSkills, professionalSummary, experience[].bullets, projects, certifications).
 * This is distinct from buildCandidateKeywordSet, which reads from a raw user profile.
 */
function buildCVKeywordSet(cv) {
    const parts = [];
    if (cv.professionalSummary) parts.push(cv.professionalSummary);
    if (cv.coreSkills && cv.coreSkills.length) parts.push(cv.coreSkills.join(' '));
    if (cv.experience && cv.experience.length) {
        cv.experience.forEach(e => {
            if (e.title) parts.push(e.title);
            if (e.company) parts.push(e.company);
            if (e.bullets && e.bullets.length) parts.push(e.bullets.join(' '));
        });
    }
    if (cv.projects && cv.projects.length) {
        cv.projects.forEach(p => {
            if (p.title) parts.push(p.title);
            if (p.description) parts.push(p.description);
        });
    }
    if (cv.certifications && cv.certifications.length) {
        cv.certifications.forEach(c => {
            if (c.name) parts.push(c.name);
            if (c.issuer) parts.push(c.issuer);
        });
    }
    return new Set(tokenize(parts.join(' ')));
}

/**
 * Computes a deterministic 0-100 match score between a candidate profile and a job,
 * based on the candidate's stated skills appearing in the job text plus general
 * keyword overlap. Runs entirely locally, no external API calls, safe to run per-item
 * across a full job list or friend list.
 */
function computeMatchScore(user, job) {
    const candidateSkills = (user.skills || []).map(s => (s || '').trim()).filter(Boolean);
    const jobTextBlob = [job.title, job.description, job.fullDescription]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();

    const matchedSkills = candidateSkills.filter(skill =>
        jobTextBlob.includes(skill.toLowerCase())
    );

    const skillCoverage = candidateSkills.length > 0
        ? matchedSkills.length / candidateSkills.length
        : 0;

    const candidateKeywords = buildCandidateKeywordSet(user);
    const jobKeywords = buildJobKeywordSet(job);

    let overlapCount = 0;
    jobKeywords.forEach(word => {
        if (candidateKeywords.has(word)) overlapCount++;
    });

    const keywordOverlap = jobKeywords.size > 0
        ? overlapCount / jobKeywords.size
        : 0;

    let percentage = Math.round((skillCoverage * 0.6 + keywordOverlap * 0.4) * 100);

    if (matchedSkills.length > 0) {
        percentage = Math.min(100, percentage + 5);
    }

    percentage = Math.max(0, Math.min(100, percentage));

    return { matchPercentage: percentage, matchedSkills };
}

/**
 * Compares a specific submitted résumé (CV object, as generated by generateResumeForUser)
 * against a job's description and returns an ATS-style keyword analysis: which of the
 * job's key terms are present in the résumé text, which are missing, and an overall
 * keyword-coverage score. Intended for job posters reviewing a candidate's or referral's
 * résumé — distinct from computeMatchScore, which works off the raw profile, not the CV.
 */
function computeATSAnalysis(cv, job) {
    if (!cv) {
        return { score: 0, matchedKeywords: [], missingKeywords: [], totalKeywords: 0 };
    }

    const jobKeywords = buildJobKeywordSet(job);
    const cvKeywords = buildCVKeywordSet(cv);

    const matchedKeywords = [];
    const missingKeywords = [];

    jobKeywords.forEach(word => {
        if (cvKeywords.has(word)) {
            matchedKeywords.push(word);
        } else {
            missingKeywords.push(word);
        }
    });

    const totalKeywords = jobKeywords.size;
    const score = totalKeywords > 0
        ? Math.round((matchedKeywords.length / totalKeywords) * 100)
        : 0;

    matchedKeywords.sort();
    missingKeywords.sort();

    return {
        score,
        matchedKeywords,
        missingKeywords: missingKeywords.slice(0, 25),
        totalKeywords
    };
}

module.exports = { computeMatchScore, computeATSAnalysis };